version: '3'

services:
  hbbs:
    container_name: hbbs
    ports:
      - 172.17.0.1:22115:21115
      - 172.17.0.1:22116:21116
      - 172.17.0.1:22116:21116/udp
      - 172.17.0.1:22118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r ${DOMAIN}:21117
    volumes:
      - ./data:/root
    depends_on:
      - hbbr
    restart: always

  hbbr:
    container_name: hbbr
    ports:
      - 172.17.0.1:22117:21117
      - 172.17.0.1:22119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    restart: always