version: '3'

services:
  hbbs:
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r ${DOMAIN}:21117
    volumes:
      - ./data:/root
    depends_on:
      - hbbr
    restart: always

  hbbr:
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    restart: always
